snowplow-incubator/common-streams

modules/loaders-common/src/test/scala/com.snowplowanalytics.snowplow.loaders/transform/SkippingSchemasSpec.scala, modules/loaders-common/src/test/scala/com.snowplowanalytics.snowplow.loaders/transform/TransformSpec.scala, project/Dependencies.scala
* New meta field `_schema_field` for each context after calling `toShreddedJson` transformation
* It also brings possiblity of parsing `Event`s from bytes, but this is going to be utilized directly in event processors.
=> Upgrade analytics-sdk to 3.2.0

modules/loaders-common/src/test/scala/com.snowplowanalytics.snowplow.loaders/transform/TransformSpec.scala, project/BuildSettings.scala, project/Dependencies.scala
This PR extends coverage of `Transform.transformEventUnstructured` unit tests to check every possible atomic field is transformed to the correct type with the correct value.
It uses [snowplow-event-generator](https://github.com/snowplow-incubator/snowplow-event-generator) to generate events. However, current latest version of Event Generator (0.6.0) doesn't populate some of the event fields at all. In order to populate all event fields, I've made [some changes on Event Generator](https://github.com/snowplow-incubator/snowplow-event-generator/pull/72) and published `0.6.1-rc2` version of Event Generator with those changes. This PR is using rc version at the moment. Event Generator version will be made 0.6.1 when it is published.
=> Extend coverage of Transform.transformEventUnstructured unit tests

modules/kafka/src/main/resources/reference.conf, modules/kinesis/src/main/resources/reference.conf, modules/loaders-common/src/main/scala/com/snowplowanalytics/snowplow/loaders/transform/BadRowsSerializer.scala, modules/loaders-common/src/test/scala/com.snowplowanalytics.snowplow.loaders/transform/BadRowsSerializerSpec.scala, modules/pubsub/src/main/resources/reference.conf
Each sink provided by `common-streams` library defines maximum accepted record size: 
* for kinesis - 1MB
* for pubsub - 10MB
* for kafka - 1MB
This PR implements badrow serializer, which makes sure those limits are not exceeded. If limit of bytes is reached, `SizeViolation` badrow is created with trimmed original payload
=> Add badrows serializer checking max size

modules/loaders-common/src/test/scala/com.snowplowanalytics.snowplow.loaders/transform/SkippingSchemasSpec.scala, modules/loaders-common/src/test/scala/com.snowplowanalytics.snowplow.loaders/transform/TransformSpec.scala, project/Dependencies.scala
By using new 3.2.1 analytics-sdk version and this change -> https://github.com/snowplow/snowplow-scala-analytics-sdk/pull/134
=> Use short `_schema_version` field from analytics-sdk

modules/kafka/src/main/resources/reference.conf, modules/kafka/src/main/scala/com/snowplowanalytics/snowplow/azure/AzureAuthenticationCallbackHandler.scala, modules/kafka/src/main/scala/com/snowplowanalytics/snowplow/sinks/kafka/KafkaSink.scala, modules/kafka/src/main/scala/com/snowplowanalytics/snowplow/sources/kafka/KafkaSource.scala, modules/kafka/src/test/scala/com/snowplowanalytics/snowplow/sinks/kafka/KafkaSinkConfigSpec.scala, modules/kafka/src/test/scala/com/snowplowanalytics/snowplow/sources/kafka/KafkaSourceConfigSpec.scala, project/Dependencies.scala
=> Kafka: authenticate with Event Hubs using OAuth2

modules/loaders-common/src/main/scala/com/snowplowanalytics/snowplow/loaders/transform/NonAtomicFields.scala, modules/loaders-common/src/test/resources/iglu-client-embedded/schemas/myvendor/myschema/jsonschema/9-0-0, modules/loaders-common/src/test/scala/com.snowplowanalytics.snowplow.loaders/transform/NonAtomicFieldsSpec.scala, modules/loaders-common/src/test/scala/com.snowplowanalytics.snowplow.loaders/transform/SkippingSchemasSpec.scala
Slightly different than filtering for unstructured events:
* For unstructured, filtering is implemented in `Transform` by filtering matching entities from events. It's executed for each entity, for each event.
* For structured, filtering is implemented in `NonAtomicFields.resolveTypes`. Resolving types is executed once per batch of events, so it's more efficient than doing it for each event in `Transform`.
We can't use this approach for unstructured events because we don't have the step of resolving types.
=> For structured data add ability to skip schemas matching criterion.

modules/loaders-common/src/main/scala/com/snowplowanalytics/snowplow/loaders/transform/Transform.scala, modules/loaders-common/src/test/scala/com.snowplowanalytics.snowplow.loaders/transform/TransformSpec.scala
Currently, the transform functions in common-loaders return a [List](https://github.com/snowplow-incubator/common-streams/blob/0.2.1/modules/loaders-common/src/main/scala/com/snowplowanalytics/snowplow/loaders/transform/Transform.scala#L83).  We construct the list by concatenating two lists: 1 for atomic fields and 1 for the self-describing entity fields ([this line](https://github.com/snowplow-incubator/common-streams/blob/0.2.1/modules/loaders-common/src/main/scala/com/snowplowanalytics/snowplow/loaders/transform/Transform.scala#L86)).
The `:::` operator is relatively expensive, especially for large lists.  And this is a “hot” function which we invoke for every single event.
If we switch the implementation to use Vector instead of List then it should be much more efficient to …
=> Use `Vector` instead of `List` in transform methods

modules/streams-core/src/main/scala/com.snowplowanalytics.snowplow/sources/internal/LowLevelSource.scala
The LowLevelSource maintains a list of what messages are in-flight but not yet acked. During graceful shutdown, it should nack everything in this list so that Pubsub can quickly re-send the messages to another pod. But because of a subtle bug, the pubsub Subscriber was getting shutdown before those messages got nacked.
=> Fix nacking unhandled pubsub messages during shutdown

modules/loaders-common/src/main/scala/com/snowplowanalytics/snowplow/loaders/transform/NonAtomicFields.scala, modules/loaders-common/src/main/scala/com/snowplowanalytics/snowplow/loaders/transform/Transform.scala
In #62 the transform method was improved to avoid the expensive `:::` operator.  But we were still converting a `List` to a `Vector` for every single event.  That conversion can be eliminated fairly easily.
=> Use `Vector` instead of `List` in transform methods: part 2

modules/it/src/test/scala/com/snowplowanalytics/snowplow/sources/kinesis/Utils.scala, modules/kinesis/src/main/resources/reference.conf, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/sources/kinesis/KinesisSource.scala, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/sources/kinesis/KinesisSourceConfig.scala, modules/kinesis/src/test/scala/com/snowplowanalytics/snowplow/sources/kinesis/KinesisSourceConfigSpec.scala, project/BuildSettings.scala
Our snowplow stream-processing apps tend to produce duplicates on AWS. It happens because KCL allows workers to "steal" shard leases from other workers.
By adjusting some KCL configuration params, we can minimize lease stealing under some circumstances:
- `workerIdentifier`: If a pod uses a consistent name, then whenever the pod restarts (e.g. after crashing or after a rollout) then the pod can re-claim leases that it previously owned before the restart
- `leaseDuration`: The KCL default is 10 seconds.  If we increase this, then we can allow a pod longer to re-claim its old leases after a restart.
=> Kinesis source options to allow less lease-stealing

.github/workflows/ci.yml, modules/it/src/test/scala/com/snowplowanalytics/snowplow/DockerPull.scala, modules/it/src/test/scala/com/snowplowanalytics/snowplow/runtime/MetricsSpec.scala, modules/it/src/test/scala/com/snowplowanalytics/snowplow/runtime/Statsd.scala, modules/it/src/test/scala/com/snowplowanalytics/snowplow/sources/kinesis/KinesisSinkSpec.scala, modules/it/src/test/scala/com/snowplowanalytics/snowplow/sources/kinesis/KinesisSourceSpec.scala, modules/it/src/test/scala/com/snowplowanalytics/snowplow/sources/kinesis/Localstack.scala, project/Dependencies.scala
Previously, we relied on org.testcontainers' method of fetching container image for StatsD. This was counted towards test timeout and rarely actually triggered the tests.
Now, the image is fetched as part of beforeAll step and handled as part of setup time that's not counted towards the timeout. If the image is already available the cost of blocking is nearly zero.
testcontainers/ryuk is a resource reaper used for cleaning things up after tests complete. In CI we only run tests once after which the VM is shut down. Ryuk fetching happens while creating a `CatsResource` that is counted towards timeout. This can take a long time in CI and rarely happens at dev time.
Therefore, for CI ryuk is now disabled.
=> Manually fetch container image before running StatsD spec

modules/streams-core/src/main/scala/com.snowplowanalytics.snowplow/sources/EventProcessingConfig.scala, modules/streams-core/src/main/scala/com.snowplowanalytics.snowplow/sources/internal/LowLevelSource.scala, modules/streams-core/src/test/scala/com.snowplowanalytics.snowplow/sources/internal/LowLevelSourceSpec.scala
common-streams has a feature in which a timed window of events is allowed to start processing before the previous window has finalized. This is a great feature for making full use of available cpu. It means are are always working the cpu hard, even if some slow I/O is required to finalize the window.
Until now, the eagerness only stretched to consecutive windows. E.g. If window 1 is still finalizing then it is allowed for window 2 to start processing; but it is not allowed for window 3 to start processing.
For Lake Loader I found it is better to let the eagerness stretch further.  E.g. window 3 is allowed to start processing even if windows 1 and 2 are both still finalizing.
This PR makes configurable how many windows may start eagerly ahead of a finalzing window.
=> Eagerness of windows should be configurable

modules/streams-core/src/main/scala/com.snowplowanalytics.snowplow/sources/internal/LowLevelSource.scala, modules/streams-core/src/test/scala/com.snowplowanalytics.snowplow/sources/internal/LowLevelSourceSpec.scala
common-streams has a feature where the first window is randomly adjusted to a different size. This helps in a deployment where a large number of pods might all start at the same time, but we pods to have mutually staggered windows, e.g. to avoid write conflicts in the lake loader.
Unfortunately I broke the feature in #64 so this fixes it again.
I also add a test so it won't get broken again.
=> Fix randomly adjusted first window size

modules/pubsub/src/main/resources/reference.conf, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/sources/pubsub/PubsubSource.scala, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/sources/pubsub/PubsubSourceConfig.scala, modules/pubsub/src/test/scala/com/snowplowanalytics/snowplow/sources/pubsub/PubsubSourceConfigSpec.scala
The PubSub Source parameter `parallelPullCount` was used to set the parallelism of the underlying Subscriber. With a higher pull count, the Subscriber can supply events more quickly to the downstream of the application, but there is more overhead.
For typical Snowplow apps, a pull count of 1 is sufficient on small instances. But when there is more cpu availalbe, the downstream app processes events more quickly, and therefore we need a higher pull count to provide the events.
This PR makes it so pull count is picked dynamically based on available cpu. Snowplow apps on bigger instances will automatically get the benefit of this change, without requiring the user to explicitly set the pull count.
=> PubSub source scale the parallel pull count with number of cores

modules/kafka/src/main/scala/com/snowplowanalytics/snowplow/sources/kafka/KafkaSource.scala, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/sources/kinesis/KinesisSource.scala, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/sources/pubsub/PubsubSource.scala, modules/streams-core/src/main/scala/com.snowplowanalytics.snowplow/sources/SourceAndAck.scala, modules/streams-core/src/main/scala/com.snowplowanalytics.snowplow/sources/internal/LowLevelSource.scala, modules/streams-core/src/test/scala/com.snowplowanalytics.snowplow/sources/internal/LowLevelSourceSpec.scala
Part of PDP-1196
The KCL is sadly not very good at crashing and exiting. If the underlying Kinesis client has errors (e.g. permissions errors) then KCL tends to stay alive and not propagate the exceptions to our application code. We want the app to crash under these circumstances because that triggers an alert.    
common-streams already has a health check feature, in which a health probe becomes unhealthy if a single event gets stuck without making progress.    
This PR leans on the existing health check feature, so it also becomes unhealthy if the Kinesis client is not regularly receiving healthy responses.    
I configured KCL to invoke our record processor every time it polls for records, even if the batch is empty. This means the health check still works even if there are no events …
=> Kinesis source must report its latency when KCL is not healthy

build.sbt, modules/runtime-common/src/main/scala/com/snowplowanalytics/snowplow/runtime/Webhook.scala, modules/runtime-common/src/test/scala/com/snowplowanalytics/snowplow/runtime/WebhookSpec.scala, project/BuildSettings.scala, project/Dependencies.scala
Several of our newer Snowplow apps send alert messages to a webhook. They all share a common configuration and implementation.  But currently the implementation is duplicated across each app.  This PR consolidates it into one place.
=> Webhook for sending alert messages

modules/runtime-common/src/main/resources/reference.conf, modules/runtime-common/src/main/scala/com/snowplowanalytics/snowplow/runtime/AppHealth.scala, modules/runtime-common/src/main/scala/com/snowplowanalytics/snowplow/runtime/HealthProbe.scala, modules/runtime-common/src/main/scala/com/snowplowanalytics/snowplow/runtime/Retrying.scala, modules/runtime-common/src/main/scala/com/snowplowanalytics/snowplow/runtime/SetupExceptionMessages.scala, modules/runtime-common/src/main/scala/com/snowplowanalytics/snowplow/runtime/Webhook.scala, modules/runtime-common/src/test/scala/com/snowplowanalytics/snowplow/runtime/AppHealthSpec.scala, modules/runtime-common/src/test/scala/com/snowplowanalytics/snowplow/runtime/HealthProbeSpec.scala, modules/runtime-common/src/test/scala/com/snowplowanalytics/snowplow/runtime/WebhookConfigSpec.scala, modules/runtime-common/src/test/scala/com/snowplowanalytics/snowplow/runtime/WebhookSpec.scala, modules/streams-core/src/main/scala/com.snowplowanalytics.snowplow/sources/SourceAndAck.scala, project/BuildSettings.scala, project/Dependencies.scala
Application health is needed for two distinct reasons:
1. Sending alerts to a monitoring webhook for setup errors. Relatedly, sending heartbeat messages to the webhook when healthy.
2. The HTTP health probe.  Needed so that the orchestration environment (kubernetes or whatever) can kill the pod when unhealthy
Several Snowplow apps each implement their own logic of when to toggle the health probe and when to send an alert.  This PR consolidates that logic into one place.
After this PR, the application code just needs to call methods on the AppHealth class.  This lib then manages webhook events and health probe, based on the current status of the AppHealth.
=> Refactor application health monitoring

modules/it/src/test/scala/com/snowplowanalytics/snowplow/sources/kinesis/Utils.scala, modules/kinesis/src/main/resources/reference.conf, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/sources/kinesis/Checkpointable.scala, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/sources/kinesis/KCLAction.scala, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/sources/kinesis/KCLScheduler.scala, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/sources/kinesis/KinesisCheckpointer.scala, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/sources/kinesis/KinesisSource.scala, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/sources/kinesis/KinesisSourceConfig.scala, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/sources/kinesis/ShardRecordProcessor.scala, modules/kinesis/src/test/scala/com/snowplowanalytics/snowplow/sources/kinesis/KinesisSourceConfigSpec.scala, modules/streams-core/src/main/scala/com.snowplowanalytics.snowplow/sources/internal/LowLevelSource.scala, project/Dependencies.scala
The common-streams Kinesis source suffers from a problem where we don't quite achieve at-least-once processing semantics near the end of a shard. The problem was in the 3rd-party fs-kinesis library, and it is not easy to fix with any small code change to that library.
Sorry I cannot provide a link here to back that up -- it is documented internally at Snowplow.
This PR re-implements our Kinesis source from scratch, this time without a dependency on fs2-kinesis.  The biggest difference is the way we block the `shardEnded` method of the KCL record processor, until all records from the shard have been written to the destination.
=> Re-implement Kinesis source without fs2-kinesis

modules/loaders-common/src/main/scala/com/snowplowanalytics/snowplow/loaders/transform/NonAtomicFields.scala
I have seen examples from our apps where cpu usage and event throughput periodically drops.  This appears to coincide with the Iglu cache expiration time.
I believe this happens because all schemas tend to expire at the same time and need to be re-fetched by iglu-scala-client. Currently, we traverse over schemas sequentially, so we need to wait for each success before fetching the next schema.  For a pipeline using many schemas, this can be a long period of downtime (several seconds) as we pause for schema resolution.
This commit changes to resolving schemas in parallel, so the downtime pauses should be shorter.
=> Resolve schemas in parallel

modules/runtime-common/src/main/resources/reference.conf, modules/runtime-common/src/main/scala/com/snowplowanalytics/snowplow/runtime/HttpClient.scala, modules/runtime-common/src/main/scala/com/snowplowanalytics/snowplow/runtime/Telemetry.scala, modules/runtime-common/src/test/scala/com/snowplowanalytics/snowplow/runtime/ConfigParserSpec.scala, modules/runtime-common/src/test/scala/com/snowplowanalytics/snowplow/runtime/MetricsConfigSpec.scala, project/Dependencies.scala
Common-streams apps require an http4s Client for:
- Iglu resolver
- Webhook monitoring alerts
- Telemetry
This commit provides a Client which is configured appropriately for these common use cases.
=> Http4s Client with configuration appropriate for common-streams apps

project/BuildSettings.scala
The heartbeat schema is now published to Iglu Central: snowplow/iglu-central#1416
We have unit tests that use the heartbeat schema.  Previously they were using a dev registry to fetch the schema.
=> Remove temporary Iglu registry used for heartbeat tests

modules/pubsub/src/main/resources/reference.conf, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/sources/pubsub/PubsubSource.scala, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/sources/pubsub/PubsubSourceConfig.scala, modules/pubsub/src/test/scala/com/snowplowanalytics/snowplow/sources/pubsub/PubsubSourceConfigSpec.scala
Previously the pubsub SDK opened just a single transport channel (roughly equivalent to a TCP channel).
Some snowplow apps we need to batch up a very large number of events from the source before acking.  In those circumstances it is good to open more streaming pulls (a type of RPC) to keep the pubsub subscription healthy.  But to open more streaming pulls we also need to open more transport channels (TCP channels) to support all the RPCs.
This commit adds a new config parameter `maxPullsPerTransportChannel`. The default value 16 is good for most apps.
=> Pubsub source open more transport channels

modules/runtime-common/src/main/resources/reference.conf, modules/runtime-common/src/test/scala/com/snowplowanalytics/snowplow/runtime/WebhookConfigSpec.scala
...as requested by the downstream consumers of this webhook
=> Change default webhook heartbeat period to 5 minutes

.github/workflows/ci.yml, .github/workflows/release.yml
sbt was removed from ubuntu image recently and we need to install it separately
=> Install sbt in github actions

modules/loaders-common/src/main/scala/com/snowplowanalytics/snowplow/loaders/transform/TypedTabledEntity.scala, modules/loaders-common/src/test/resources/iglu-client-embedded/schemas/myvendor/test_empty_prop/jsonschema/1-0-0, modules/loaders-common/src/test/resources/iglu-client-embedded/schemas/myvendor/test_empty_prop/jsonschema/1-0-1, modules/loaders-common/src/test/scala/com.snowplowanalytics.snowplow.loaders/transform/NonAtomicFieldsSpec.scala
This PR fixes a bug introduced after `0.8.0-M2`. See the snippet below for a simpler visualization.
```scala
scala> import cats.data.NonEmptyList
import cats.data.NonEmptyList
scala> import cats.syntax.all._
import cats.syntax.all._
scala> def parseInt(s: String): Option[Int] = Either.catchOnly[NumberFormatException](s.toInt).toOption
def parseInt(s: String): Option[Int]
scala> NonEmptyList.of("1", "2", "3").traverse(parseInt)
val res0: Option[cats.data.NonEmptyList[Int]] = Some(NonEmptyList(1, 2, 3))
scala> NonEmptyList.of("1", "two", "3").traverse(parseInt)
val res1: Option[cats.data.NonEmptyList[Int]] = None
scala> NonEmptyList.of("1", "two", "3").toList.flatMap(parseInt).toNel
val res2: Option[cats.data.NonEmptyList[Int]] = Some(NonEmptyList(1, 3))
```
=> Fix TypedTabledEntity build

modules/loaders-common/src/test/scala/com.snowplowanalytics.snowplow.loaders/transform/TransformUnstructuredSpec.scala, project/Dependencies.scala
We recommend that Snowplow entities should be JSON *objects* only. But technically it is possible for them to be something else, e.g. a JSON array.
Before this fix, we accidentally erased the original value if a context was not a JSON object. The bug only affected unstructed destinations, e.g. the Snowflake loader.
The fix was implented in snowplow/snowplow-scala-analytics-sdk#137 and is imported here.
=> Fix for `_schema_version` overriding non-object entity data

modules/loaders-common/src/test/resources/iglu-client-embedded/schemas/myvendor/myschema/jsonschema/10-0-0, modules/loaders-common/src/test/resources/iglu-client-embedded/schemas/myvendor/myschema/jsonschema/10-0-1, modules/loaders-common/src/test/scala/com.snowplowanalytics.snowplow.loaders/transform/NonAtomicFieldsSpec.scala, project/Dependencies.scala
See snowplow/schema-ddl#213
When a schema is evolved (e.g. from `1-0-0` to `1-0-1`) we create a merged struct column combining fields from new and old schema.
For some loaders it is important that newly-added nested fields come after the original fields. E.g. Lake Loader with Hudi and Glue sync enabled.
=> Preserve original field order when merging schemas

modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/sources/kinesis/KinesisSource.scala
In the Kinesis Source, we terminate the inner stream of events whenever we reach the end of a Kinesis shard. Terminating the inner stream is important, because it forces the application to fully process and checkpoint any outstanding events, and this unblocks our KCL record processor from checkpointing the end of the shard.
Before this PR, we terminated the inner stream for _every_ shard end. But terminating the stream is quite inefficient, and during a re-sharding we probably reach many shard ends at similar time. This PR changes things so we try to handle many shard ends at the same time. During re-sharding, this should reduce the number of times we need to terminate the inner stream.
=> Kinesis source improve management of shard ends

modules/pubsub/src/main/resources/reference.conf, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/pubsub/FutureInterop.scala, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/sources/pubsub/PubsubBatchState.scala, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/sources/pubsub/PubsubCheckpointer.scala, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/sources/pubsub/PubsubRetryOps.scala, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/sources/pubsub/PubsubSource.scala, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/sources/pubsub/PubsubSourceConfig.scala, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/sources/pubsub/Utils.scala, modules/pubsub/src/test/scala/com/snowplowanalytics/snowplow/sources/pubsub/PubsubSourceConfigSpec.scala
The previous implementation of the PubSub Source was a wrapper around `Subscriber` provided by the 3rd-party pubsub sdk. That `Subscriber` is a wrapper around a lower-level GRPC stub. It used the "Streaming Pull" GRPC method to fetch messages from PubSub.
This commit abandons using the `Subscriber` and instead wraps the GRPC stub directly. It uses the "Unary Pull" GRPC method to fetch messages from PubSub.
We found that "Unary Pull" alleviates a problem in which PubSub occasionally re-delivers the same messages, causing downstream duplicates. The problem happened especially in apps like Lake Loader, which builds up a very large number of un-acked messages and then acks them all in one go at the end of a timed window.
Compared with the previous Source implementation it has these …
=> PubSub Source using Unary Pull

modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/sources/kinesis/KinesisSource.scala
This fixes a possible problem in which some Kinesis shards progress more quickly than others. Each KCL shard processor has its own thread, and each calls `queue.put()` on the synchronous queue.  It is possible that by luck some shard/threads were having their `put()` accepted by a consumer more quickly.
=> Enable fairness on Kinesis Source's SynchronousQueue

modules/it/src/test/scala/com/snowplowanalytics/snowplow/runtime/MetricsSpec.scala, modules/it/src/test/scala/com/snowplowanalytics/snowplow/sources/kinesis/KinesisSourceSpec.scala, modules/it/src/test/scala/com/snowplowanalytics/snowplow/sources/kinesis/Utils.scala, modules/kafka/src/main/scala/com/snowplowanalytics/snowplow/sources/kafka/KafkaSource.scala, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/sources/kinesis/KinesisSource.scala, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/sources/pubsub/PubsubSource.scala, modules/runtime-common/src/main/scala/com/snowplowanalytics/snowplow/runtime/Metrics.scala, modules/streams-core/src/main/scala/com.snowplowanalytics.snowplow/sources/EventProcessingConfig.scala, modules/streams-core/src/main/scala/com.snowplowanalytics.snowplow/sources/SourceAndAck.scala, modules/streams-core/src/main/scala/com.snowplowanalytics.snowplow/sources/TokenedEvents.scala, modules/streams-core/src/main/scala/com.snowplowanalytics.snowplow/sources/internal/LowLevelEvents.scala, modules/streams-core/src/main/scala/com.snowplowanalytics.snowplow/sources/internal/LowLevelSource.scala, modules/streams-core/src/test/scala/com.snowplowanalytics.snowplow/sources/internal/LowLevelSourceSpec.scala
Currently in common-streams apps, the _application_ (i.e. not this library) is responsible for tracking latency of events consumed from the stream.  Because of the way it is implemented in the apps, if an event gets stuck (e.g. cannot be written to destination) then the latency drops to zero for the period when the app is retrying the stuck event.
This commit aims to fix the problem where the `latency_millis` metric wrongly drops to zero.
1. The source itself now tracks the latency of the event which is currently being processed by the downstream application.
2. The Metrics class allows metric starting values to be wrapped in and Effect, i.e. `F[Metrics.State]`. This means the application can pass in the latency reported by the Source.
=> Sources should report stream latency of stuck events

modules/streams-core/src/main/scala/com.snowplowanalytics.snowplow/sources/EventProcessingConfig.scala, modules/streams-core/src/main/scala/com.snowplowanalytics.snowplow/sources/internal/LowLevelSource.scala, modules/streams-core/src/test/scala/com.snowplowanalytics.snowplow/sources/internal/LowLevelSourceSpec.scala
This change affects windowing apps e.g. Lake Loader.
Before this change, the first window was a random size, to avoid write conflicts between several loaders finishing their windows at similar times. After this change, the first window is still random, but sized in the ranged 25% to 50% of the regular window size. This was shown in Lake Loader to give a smoother starting cpu profile, and it prevents the loader from pulling in too many events into the first window.
=> Ensure first window is always small

modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/sources/pubsub/PubsubSource.scala
The `prefetchN` in the pubsub source was complicated because:
1. The preceding `parEvalMapUnordered` effectively does a pre-fetch already
2. PrefetchN works in chunks, so there was a danger our Source was pre-fetching more batches from pubsub than expected.
3. It gave a double-meaning to the `parallelPullCount` config param, because the same param got used in two places.  Which is just confusing.
Moreover, I found it just wasn't needed.  The input rate of this Source is high enough without the prefetch.
=> Remove prefetch from pubsub source

modules/it/src/test/scala/com/snowplowanalytics/snowplow/sources/kinesis/Utils.scala, modules/kafka/src/main/resources/reference.conf, modules/kafka/src/main/scala/com/snowplowanalytics/snowplow/sources/kafka/KafkaSource.scala, modules/kafka/src/main/scala/com/snowplowanalytics/snowplow/sources/kafka/KafkaSourceConfig.scala, modules/kafka/src/test/scala/com/snowplowanalytics/snowplow/sources/kafka/KafkaSourceConfigSpec.scala, modules/kinesis/src/main/resources/reference.conf, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/sources/kinesis/KinesisSource.scala, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/sources/kinesis/KinesisSourceConfig.scala, modules/kinesis/src/test/scala/com/snowplowanalytics/snowplow/sources/kinesis/KinesisSourceConfigSpec.scala, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/sources/pubsub/PubsubSource.scala, modules/streams-core/src/main/scala/com.snowplowanalytics.snowplow/sources/internal/LowLevelSource.scala, modules/streams-core/src/test/scala/com.snowplowanalytics.snowplow/sources/internal/LowLevelSourceSpec.scala
In snowplow-incubator/snowflake-loader#57 we added code to the snowflake loader so it checkpoints once every 10 seconds instead of once per batch. This meant we could decrease the write-throughput requirements of the DynamoDB table.
This commit moves the logic over here into common-streams so that all loaders get the benefit of this improvement.
=> Debounce how often we checkpoint progress

modules/kafka/src/main/resources/reference.conf, modules/kafka/src/test/scala/com/snowplowanalytics/snowplow/sources/kafka/KafkaSourceConfigSpec.scala
This PR adds `group.instance.id` to default kafka consumer configuration, changing our kafka consumers' membership from dynamic to static to prevent partition rebalancing happening during pod crash/restarts.
Note that we don't set `session.timeout.ms` explicitly and rely on the current default value of `45 seconds`. The reason of not picking a longer session timeout comes from horizontal scaling. A long, e.g. 3 minutes, session timeout means that the partition assigned to an evicted pod won't be processed for 3 minutes until broker recognize it. We want broker to be aware of evicted pods as soon as possible & prevent broker from triggering a partition rebalance in case of pod restarts at the same time.
ref: [PDP-1797](https://snplow.atlassian.net/browse/PDP-1797)
[PDP-1797]: …
=> Add group.instance.id to kafka consumer config

modules/loaders-common/src/main/scala/com/snowplowanalytics/snowplow/loaders/transform/NonAtomicFields.scala, modules/loaders-common/src/test/resources/iglu-client-embedded/schemas/myvendor/a.b.c/jsonschema/1-0-0, modules/loaders-common/src/test/resources/iglu-client-embedded/schemas/myvendor/a_b.c/jsonschema/1-0-0, modules/loaders-common/src/test/resources/iglu-client-embedded/schemas/myvendor/a_b_c/jsonschema/1-0-0, modules/loaders-common/src/test/resources/iglu-client-embedded/schemas/myvendor/d.e.f/jsonschema/1-0-0, modules/loaders-common/src/test/resources/iglu-client-embedded/schemas/myvendor/d_e_f/jsonschema/1-0-0, modules/loaders-common/src/test/scala/com.snowplowanalytics.snowplow.loaders/transform/NonAtomicFieldsSpec.scala, modules/loaders-common/src/test/scala/com.snowplowanalytics.snowplow.loaders/transform/SkippingSchemasSpec.scala
Jira ref: PDP-1799
It is possible to get same column name from two different schemas. One example pair is `a.b.c/d` and `a.b/c_d`. Field names of both become `a_b_c_d`. This creates problem on the loader side since two entities with two different schemas are tried to be loaded to same column.
This PR makes necessary changes to return error in this scenario.
=> Return error from 'resolveTypes' when schemas have clashing column names

modules/it/src/test/scala/com/snowplowanalytics/snowplow/sources/kinesis/Utils.scala, modules/kafka/src/main/scala/com/snowplowanalytics/snowplow/sinks/kafka/KafkaSinkConfig.scala, modules/kafka/src/main/scala/com/snowplowanalytics/snowplow/sinks/package.scala, modules/kafka/src/test/scala/com/snowplowanalytics/snowplow/sinks/kafka/KafkaSinkConfigSpec.scala, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/sinks/kinesis/KinesisSinkConfig.scala, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/sinks/package.scala, modules/kinesis/src/test/scala/com/snowplowanalytics/snowplow/sinks/kinesis/KinesisSinkConfigSpec.scala, modules/nsq/src/main/scala/com/snowplowanalytics/snowplow/sinks/nsq/NsqSinkConfig.scala, modules/nsq/src/main/scala/com/snowplowanalytics/snowplow/sinks/package.scala, modules/nsq/src/test/scala/com/snowplowanalytics/snowplow/sinks/nsq/NsqSinkConfigSpec.scala, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/sinks/package.scala, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/sinks/pubsub/PubsubSinkConfig.scala, modules/pubsub/src/test/scala/com/snowplowanalytics/snowplow/sinks/pubsub/PubsubSinkConfigSpec.scala
In Enrich, the failed sink is optional. But it is convenient to provide defaults in the reference.conf file for some of the sink's fields.
This commit re-defines the sink configs, and provides a JSON decoder for an optional sink.
=> Sink configs should allow for optional sinks

modules/kafka/src/main/scala/com/snowplowanalytics/snowplow/streams/kafka/package.scala, modules/nsq/src/main/scala/com/snowplowanalytics/snowplow/streams/nsq/package.scala
This amends the feature added in #122.  When I came to use the factories in an app, I found the syntax is cumbersome, because the factory's type is `Factory[F, KafkaSourceConfigM[Id], KafkaSinkConfig]`.  This PR just defines a shorthand for the type, so in the app I can pass it around with the simple type `KafkaFactory[F]`.
=> Define sink factory types for easier imports in apps

modules/kafka/src/main/scala/com/snowplowanalytics/snowplow/streams/kafka/sink/KafkaSink.scala, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/streams/kinesis/sink/KinesisSink.scala, modules/nsq/src/main/scala/com/snowplowanalytics/snowplow/streams/nsq/sink/NsqSink.scala, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/streams/pubsub/sink/PubsubSink.scala, modules/streams-core/src/main/scala/com.snowplowanalytics.snowplow/streams/Sink.scala
We want to start using the common-streams sinks in the snowplow collector. Until now, common-streams only discovers a sink is unavailable if it fails to send events to the sink. But the collector has a requirement that it needs to know the health of the sink immediately upon startup, see snowplow/stream-collector#276
This commit adds a new method `isHealthy` to the `Sink` trait. Implementations of `Sink` should probe the external resource to check its health.
=> Add new method `isHealthy` to sinks

modules/pubsub/src/main/resources/reference.conf
Default maxRecordSize of Pubsub sink is reduced to make Pubsub sink safer.
=> Reduce default maxRecordSize of Pubsub sink to 9 MB

modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/streams/kinesis/source/KCLScheduler.scala, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/streams/kinesis/source/ShardRecordProcessor.scala
Jira ref: [PDP-2176](https://snplow.atlassian.net/browse/PDP-2176)
1. Catches `InterruptedException` caused by KCL's shutdown
2. Uses a `NullMetricsFactory` to disable cloudwatch metrics
Both of these changes lead to fewer noisy unhelpful log lines during shutdown
[PDP-2176]: https://snplow.atlassian.net/browse/PDP-2176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Clean shutdown logs of kinesis source
